### PR TITLE
tons of staging stuff

### PR DESCRIPTION
**Pull request by aappling-usgs**
@jread-usgs this PR will get us up to date - i don't think there'll be any changes to how write_ts is working for you, but you never know....

### CODE REVIEW

**Comment by aappling-usgs** [comment]
looks like the same old autobuild errors. still no idea why `parse_ts_path` fails in the autobuild environment. maybe they don't actually have file paths there?

**Comment by jread-usgs** [comment]
Probably want to increment the minor version on this? I know we haven't been consistent with that, but it will help us internally at least (e.g., oh, you are on version 0.7.3? that's why your styx_sites fail).

**Comment by jread-usgs** [comment]
Also, I get those errors locally now:

```
Running the tests in ‘tests/testthat.R’ failed.
Last 13 lines of output:
  OK: 60 SKIPPED: 0 FAILED: 9
  1. Failure (at test-mda_helpers.R#66): ts file paths can be made and parsed 
  2. Failure (at test-mda_helpers.R#67): ts file paths can be made and parsed 
  3. Failure (at test-mda_helpers.R#68): ts file paths can be made and parsed 
  4. Failure (at test-mda_helpers.R#69): ts file paths can be made and parsed 
  5. Failure (at test-mda_helpers.R#70): ts file paths can be made and parsed 
  6. Failure (at test-mda_helpers.R#71): ts file paths can be made and parsed 
  7. Failure (at test-mda_helpers.R#72): ts file paths can be made and parsed 
  8. Failure (at test-mda_helpers.R#73): ts file paths can be made and parsed 
  9. Failure (at test-mda_helpers.R#74): ts file paths can be made and parsed 
```

**Comment by jread-usgs** [comment]
```R
testthat::expect_equal(mda.streams:::parse_ts_path("nwis_12398074-ts_doobs_nwis.tsv.gz", use_names=FALSE), data.frame(site_name="nwis_12398074", ts_name="ts_doobs_nwis", stringsAsFactors=FALSE))
Error: mda.streams:::parse_ts_path("nwis_12398074-ts_doobs_nwis.tsv.gz", use_names = FALSE) not equal to data.frame(site_name = "nwis_12398074", ts_name = "ts_doobs_nwis", stringsAsFactors = FALSE)
Attributes: < Component “class”: Lengths (1, 2) differ (string compare on first 1) >
Attributes: < Component “class”: 1 string mismatch >
```
I can fix those if you would like

**Comment by aappling-usgs** [comment]
sure, if you can fix them, that'd be great! what's the cause? i've had trouble debugging them because i can't replicate them.

in the meantime, if you don't want to merge the full PR, you just need to change the make_site_name definition to this:
```
make_site_name <- function(sitenum, database=c("nwis", "styx")) {
```
which should also fix parse_site_name for the fake-data sites

**Comment by jread-usgs** [comment]
This looks good, but let's fix tests on the next round after we figure out why your returns from those functions are different than expected

**Comment by aappling-usgs** [comment]
resolves #108

**Pull request merged**
