### PR TITLE
config handling & solar.time/date refactor

### PR DESCRIPTION
**Pull request by aappling-usgs**
- updates to `modernize_metab_model` to reflect streamMetabolizer changes through v 0.9.0
- `var_src_codes` is now derived internally (again) - revert to SB on GRAN build simultaneous w/ streamMetabolizer GRAN build
- config handling: bug fixes, code streamlining
- switch from local.time to solar.time, app.solar.time, any.solar.time (reflects streamMetabolizer changes through 0.8.0 i think)

### CODE REVIEW

**Comment by aappling-usgs** [comment]
@jread-usgs - let's wait for the CI builds, but i think/hope this will be all my updates. pretty much separate from what you and @lindsaycarr are working on, anyway.

both of you, note that if you pull this version, you will also need updated streamMetabolizer (through 0.8.0 or possibly even the up-and-coming 0.9.0. i hope just 0.8.0.)

**Comment by jread-usgs** [comment]
Thanks @aappling-usgs

**Comment by aappling-usgs** [comment]
both CI builds are currently failing on `Package required and available but unsuitable version: 'streamMetabolizer'`. This is because they're looking to the master branch of USGS-R/streamMetabolizer, but only the develop branch is >= v0.8.0

**Comment by aappling-usgs** [comment]
well, coverage is abysmal and may always be for this pkg, but i'm satisfied for now. @jread-usgs & @lindsaycarr, if these changes seem compatible with what you're doing, please give :+1: and/or merge. 

when you pull this version of `mda.streams`, you'll be required to switch to `streamMetabolizer 0.8.0` or later. i don't think that version will cause problems for either of you. i'm working on a PR to `streamMetabolizer 0.9.1` right now, so if you need the `0.8.0` version specifically, do this:
```
devtools::install_github("USGS-R/streamMetabolizer#150")
```

Re: the PR to `streamMetabolizer 0.9.1`:
- @lindsaycarr - with apologies, `streamMetabolizer 0.9.1` is going to break your beautiful `get_ts` function. can we fix it at our meeting tomorrow? or if you need the fix sooner, let me know and i'll stop by. it's not hard, just useful to have insider information on what's changed. 
- @jread-usgs - i think the `streamMetabolizer 0.9.1` PR to won't matter to what you're doing in `mda.streams`. but might be good to update to that one in the nearish future (after i merge it, when you're ready to debug any conflicts w/ your code) just to be sure.

**Comment by lindsaycarr** [comment]
@aappling-usgs I'm not working on it today at all, my next steps were going to be worked on at our meeting anyways. Thanks for the heads up!

**Pull request merged**
