### PR TITLE
Stale set of commits

### PR DESCRIPTION
**Pull request by jread-usgs**
@aappling-usgs sorry, this should have been checked in much earlier. I think part of it is the unresolved `get_nldas_df` which is for getting baro and other meteorological variables. 

Want to take a look? Can treat as a work in progress if needed, or I can close this PR and set up a feature branch.

### CODE REVIEW

**Comment by aappling-usgs** [comment]
Most of the PR looks really straightforward. I can only find `get_nldas_df` in one place - in the NAMESPACE. Does it exist in some preliminary form somewhere? Maybe just move it from the NAMESPACE to an Issue, and/or put a stop("unimplemented function") in the first lines of a dummy function? Is there an official "work in progress" procedure?

**Comment by jread-usgs** [comment]
This one isn't ready for prime-time. I will make a few changes and resubmit. 

As for work in progress that is going to take longer than a day to implement, I would suggest we use feature branches for that to separate things so that we can still make progress on other parts of the package. 

Are you up for that in the future? Should we discuss the procedure?

**Comment by aappling-usgs** [comment]
Sure, branches sound like a good idea for long-running projects.

**Comment by aappling-usgs** [comment]
@jread-usgs are you ready for a merge after appveyor & travis clear?

**Comment by jread-usgs** [comment]
yep, was just waiting on that.

So, this new `geoknife` pattern is an improvement, but the services it is hitting for NLDAS are currently terribly slow. Luckily, that's just one of the services it has access to. I'd like to go over that package w/ you when I get back.

**Comment by aappling-usgs** [comment]
Sounds good! I'd like to hear about it.

On Tue, Apr 28, 2015 at 4:04 PM, Jordan S Read <notifications@github.com>
wrote:

> yep, was just waiting on that.
>
> So, this new geoknife pattern is an improvement, but the services it is
> hitting for NLDAS are currently terribly slow. Luckily, that's just one of
> the services it has access to. I'd like to go over that package w/ you when
> I get back.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/USGS-R/mda.streams/pull/60#issuecomment-97206388>.
>



-- 
Alison Appling
Postdoctoral Fellow, USGS Powell Center
USGS Center for Integrated Data Analytics and University of Wisconsin -
Madison
Phone: (608) 821-3927

**Pull request merged**
