### PR TITLE
dataRetrieval update.

### PR DESCRIPTION
**Pull request by ldecicco-USGS**

### CODE REVIEW

**Comment by jread-usgs** [comment]
you rock! :dart:

**Comment by ldecicco-USGS** [comment]
Appveyor needs geoknife, presumably travis too.

**Comment by jread-usgs** [comment]
whoops. thanks for catching my loose ends

**Comment by ldecicco-USGS** [comment]
We still need to figure out how to turn warnings to errors in these CIs. There are some older warnings hanging around...

**Pull request merged**
