### PR TITLE
post ts support for stream_metab_usa

### PR DESCRIPTION
**Pull request by jread-usgs**
This has merge issues, but I am leaving it open and will resolve. These changes were required for me to do the remake for `stream_metab_usa` for binary timeseries

### CODE REVIEW

**Comment by aappling-usgs** [comment]
@jread-usgs, you interested in renaming this PR? as far as i can tell this isn't about archiving tses, is it?

**Comment by jread-usgs** [comment]
renamed ;)

Will be cleaning this up soonish.

**Comment by jread-usgs** [comment]
ok, cleaned up conflicts.

**Comment by aappling-usgs** [comment]
:+1:

**Pull request merged**
