### PR TITLE
Initial start.

### PR DESCRIPTION
**Pull request by ldecicco-USGS**
Not working...not complete, but it's how I'd start. 

I can work on it a bit more this afternoon if you want, or you can see where I'm going with in and run.

### CODE REVIEW

**Comment by ldecicco-USGS** [comment]
Whoops
Didn't upstream pull

**Comment by ldecicco-USGS** [comment]
Well, have a look at:

https://github.com/ldecicco-USGS/mda.streams/blob/master/R/init_nwis_sites.R

**Comment by jread-usgs** [comment]
we'll see what #judgementbot thinks

**Comment by jread-usgs** [comment]
oh my, that is clean

**Comment by ldecicco-USGS** [comment]
Doesn't do the date check yet. Or multiple data descriptors

**Pull request closed without merging**
